nama   = input("Nama                    : ")
nim    = input("NIM                     : ")
kelas  = input("Kelas Paralel           : ")
ttl    = input("Tempat/Tanggal Lahir    : ")
alamat = input("Alamat                  : ")
hobby  = input("Hobby                   : ")
no_hp  = input("Nomor HP                : ")

print("\n")
print(f"Nama                    : {nama}")
print(f"NIM                     : {nim}")
print(f"Kelas Paralel           : {kelas}")
print(f"Tempat/Tanggal Lahir    : {ttl}")
print(f"Alamat                  : {alamat}")
print(f"Hobby                   : {hobby}")
print(f"Nomor HP                : {no_hp}")